version: '2'

services:
  app:
    image: 'docker-spring-boot-colloquio-tecnico:latest'
    build:
      context: .
    container_name: colloquio-tecnico-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.20.0.3:5432/testtecnico
      - SPRING_DATASOURCE_USERNAME=lorenzo
      - SPRING_DATASOURCE_PASSWORD=lorenzo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2  # Replace with the desired fixed IP address

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=lorenzo
      - POSTGRES_PASSWORD=lorenzo
      - POSTGRES_DB=testtecnico
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3  # Replace with the desired fixed IP address

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
